### PR TITLE
fix(awstf): support SQL deployments without migrations using Terraform

### PR DESCRIPTION
**Pull request by jyecusch**
Allows SQL databases to be deployed using the awstf provider, without configuring database migrations.

### CODE REVIEW

**Comment by davemooreuws** [comment]
Tested with prisma, there are some issues:

1. Works the first deployment.
2. Second deployment the code build job migration does not trigger again

**Comment by jyecusch** [comment]
> Tested with prisma, there are some issues:
> 
> 1. Works the first deployment.
> 2. Second deployment the code build job migration does not trigger again

Did that already occur before this change or is it a new issue?

**Comment by davemooreuws** [comment]
> > Tested with prisma, there are some issues:
> > 
> > 1. Works the first deployment.
> > 2. Second deployment the code build job migration does not trigger again
> 
> Did that already occur before this change or is it a new issue?

This PR only, it isn't detecting a change with the image id.

**Review by tjholm — APPROVED** [review]

**Comment by jyecusch** [comment]
> > > Tested with prisma, there are some issues:
> > > 
> > > 1. Works the first deployment.
> > > 2. Second deployment the code build job migration does not trigger again
> > 
> > 
> > Did that already occur before this change or is it a new issue?
> 
> Looks like it occurred before, it isn't detecting a change with the image id.

Makes sense, we'll look at a separate fix for that (probably today)

**Pull request merged**
